# **List[]**

In [ ]:
list1=[10,20,30,40,50]
list1

[10, 20, 30, 40, 50]

In [ ]:
list1.append(60)
list1

[10, 20, 30, 40, 50, 60]

In [ ]:
list2=[70,80,90]
list2

[70, 80, 90]

In [ ]:
list1.extend(list2)
list1

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
list1.insert(0,5)
list1

[5, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
list1.remove(5)
list1

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
list1.pop(1)
list1

[10, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
list1.index(30)

1

In [ ]:
list1.index(90)

7

In [ ]:
list1.append(70)
list1

[10, 30, 40, 50, 60, 70, 80, 90, 70]

In [ ]:
list1.count(70)

2

In [ ]:
list1.sort()
list1

[10, 30, 40, 50, 60, 70, 70, 80, 90]

In [ ]:
list1.sort(reverse=True)
list1

[90, 80, 70, 70, 60, 50, 40, 30, 10]

In [ ]:
list1.reverse()
list1

[10, 30, 40, 50, 60, 70, 70, 80, 90]

In [ ]:
list1.clear()
list1

[]

# **Tuple()**

In [ ]:
tuple1=("Sakshi","Pratiksha","Mrunmayi")
tuple1

('Sakshi', 'Pratiksha', 'Mrunmayi')

In [ ]:
tuple1[1].replace("Pratiksha","Pratu")

'Pratu'

In [ ]:
tuple1[1]="samiksha"

# Tuples in Python are immutable. Once created, their elements cannot be changed, added, or removed. That’s why when we try students[1] = "samiksha", Python throws a TypeError.

TypeError: 'tuple' object does not support item assignment

# **Set{}**

In [ ]:
set1={1,2,3,4,5,6,6,4,3,7,5,7,8}
type(set1)
set1

# we Created a set as set1={1,2,3,4,5,6,6,4,3,7,5,7,8} which consists of some duplicate values. and we printed the set1.
#  After printing the set1 we got the only single/original/non-duplicated values, because the set is not allowing the duplicate values.

# **Dictionary={Key:Value}**

In [ ]:
dict1={"Name":"Pratiksha",
       "Age":21,
       "City":"Pune"
       }
dict1

In [ ]:
dict1["Age"]=22
dict1

In [ ]:
dict1["Email"]="pratikshamhaske2004@gmail.com"
dict1

In [232]:
Age=int(input("Enter age: "))

if Age>=18:
  print("Eligible for Voting")
else:
  print("Not eligible for voting")

Enter age: 78
Eligible for Voting


In [233]:
marks=int(input("enter Marks obtained: "))

if marks>=90:
  print('A Grade')
elif(marks>=75):
  print("B Grade")
elif(marks>50):
  print("C Grade")
else:
  print("Fail")


enter Marks obtained: 88
B Grade


In [234]:
num=int(input("Enter Number: "))
if num>0:
  if num%2==0:
    print(num," Positive and even")
  else:
    print(num," Positive and odd")
elif num==0:
  print("number is Zero")
else:
  print(num, " is Negative")

Enter Number: 9
9  Positive and odd


# **Numpy**

In [235]:
import numpy as np

In [236]:
scalar=np.array(5)
print("Scalar:\n",scalar)

Scalar:
 5


In [237]:
arr_1d=np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [238]:
arr_2d=np.array([[11,22,33],[44,55,66]])
print(arr_2d)

[[11 22 33]
 [44 55 66]]


In [239]:
random_array=np.random.randint(0,101,size=(4,4))
random_array

array([[55, 42, 80, 43],
       [ 1, 60, 49, 35],
       [70, 83, 75, 19],
       [43, 72, 12, 28]])

In [240]:
array_3d=np.array([[10,20,30],[70,60,50],[30,40,50]])
array_3d

array([[10, 20, 30],
       [70, 60, 50],
       [30, 40, 50]])

In [241]:
import pandas as pd
df_array_3d=pd.DataFrame(array_3d)
df_array_3d

0   1   2
0  10  20  30
1  70  60  50
2  30  40  50

In [242]:
df_array_3d=pd.DataFrame(array_3d,columns=['A','B','C'])
df_array_3d

A   B   C
0  10  20  30
1  70  60  50
2  30  40  50

In [290]:
data={"Name":["Pratiksha","Mrunmayi","Sakshi","Snehal","Shweta","kalyani","Shreya","Siddhi","Akshada","Yojana","Pratiksha"],
      "Age":[20,21,22,23,21,22,23,22,23,21,20],
      "City":["Pune","Pune","Nashik","Nashik","Sangamner","Sangamner","Dhule","Mumbai","Mumbai","Sangamner","Pune"],
      "Salary":[22000,22000,23000,24000,25000,21000,30000,40000,50000,25000,22000]}
df=pd.DataFrame(data)
df

Name  Age       City  Salary
0   Pratiksha   20       Pune   22000
1    Mrunmayi   21       Pune   22000
2      Sakshi   22     Nashik   23000
3      Snehal   23     Nashik   24000
4      Shweta   21  Sangamner   25000
5     kalyani   22  Sangamner   21000
6      Shreya   23      Dhule   30000
7      Siddhi   22     Mumbai   40000
8     Akshada   23     Mumbai   50000
9      Yojana   21  Sangamner   25000
10  Pratiksha   20       Pune   22000

In [291]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    11 non-null     object
 1   Age     11 non-null     int64 
 2   City    11 non-null     object
 3   Salary  11 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 484.0+ bytes


In [292]:
df.describe()

Age        Salary
count  11.000000     11.000000
mean   21.636364  27636.363636
std     1.120065   9200.790480
min    20.000000  21000.000000
25%    21.000000  22000.000000
50%    22.000000  24000.000000
75%    22.500000  27500.000000
max    23.000000  50000.000000

In [293]:
df.select_dtypes(include=object)

Name       City
0   Pratiksha       Pune
1    Mrunmayi       Pune
2      Sakshi     Nashik
3      Snehal     Nashik
4      Shweta  Sangamner
5     kalyani  Sangamner
6      Shreya      Dhule
7      Siddhi     Mumbai
8     Akshada     Mumbai
9      Yojana  Sangamner
10  Pratiksha       Pune

In [294]:
df.drop(columns="City")

Name  Age  Salary
0   Pratiksha   20   22000
1    Mrunmayi   21   22000
2      Sakshi   22   23000
3      Snehal   23   24000
4      Shweta   21   25000
5     kalyani   22   21000
6      Shreya   23   30000
7      Siddhi   22   40000
8     Akshada   23   50000
9      Yojana   21   25000
10  Pratiksha   20   22000

In [295]:
df['Salary'].isnull().sum()

np.int64(0)

In [296]:
df['Salary'].mean()

np.float64(27636.363636363636)

In [297]:
df['Salary'].fillna(df['Salary'].mean())

0     22000
1     22000
2     23000
3     24000
4     25000
5     21000
6     30000
7     40000
8     50000
9     25000
10    22000
Name: Salary, dtype: int64

In [298]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [299]:
df.duplicated().sum()

np.int64(1)

In [304]:
df=df.drop_duplicates()

In [305]:
df.duplicated().sum()

np.int64(0)